# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.League')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name', 'league')]),
        ),
    ]
