# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='alert',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Watcher'),
        ),
        migrations.AlterUniqueTogether(
            name='watcher',
            unique_together=set([('team', 'user', 'notification_method', 'hours_before')]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('team', 'game_datetime', 'seatgeek_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together=set([('watcher', 'event', 'alert_time')]),
        ),
    ]
